name: ruben-snake-cmd
version: '0.2.3'
summary: Command-line version of the classic Snake game
description: |
  Command-line version of the classic Snake game.

  Run the game using the following command:
     ruben-snake-cmd

  For more information, see: https://github.com/Ruben9922/snake-cmd/blob/master/README.md.
license: GPL-3.0
confinement: strict
base: core18

parts:
  ruben-snake-cmd:
    plugin: python
    source: .

apps:
  ruben-snake-cmd:
    command: ruben-snake-cmd
